config/routes.rb
  devise_scope :user do
    get "/enter", to: "registrations#new", as: :sign_up
    get "/confirm-email", to: "devise/confirmations#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  scope "(/locale/:locale)", defaults: { locale: nil } do
    get "/locale/:locale" => "stories#index"
    require "sidekiq/web"
    require "sidekiq_unique_jobs/web"
    require "sidekiq/cron/web"

    authenticated :user, ->(user) { user.tech_admin? } do
      Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
      Sidekiq::Web.set :sessions, Rails.application.config.session_options
      Sidekiq::Web.class_eval do
        use Rack::Protection, origin_whitelist: [URL.url] # resolve Rack Protection HttpOrigin
      end
      mount Sidekiq::Web => "/sidekiq"
      mount FieldTest::Engine, at: "abtests"
    end

    namespace :resource_admin do
      DashboardManifest::DASHBOARDS.each do |dashboard_resource|
        resources dashboard_resource
      end

      root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
    end

    namespace :admin do
      get "/", to: redirect("/admin/articles")

      authenticate :user, ->(user) { user.has_role?(:tech_admin) } do
        mount Blazer::Engine, at: "blazer"

        flipper_ui = Flipper::UI.app(Flipper,
                                     { rack_protection: { except: %i[authenticity_token form_token json_csrf
                                                                     remote_token http_origin session_hijacking] } })
        mount flipper_ui, at: "feature_flags"
      end

      resources :articles, only: %i[index show update]
      resources :broadcasts
      resources :buffer_updates, only: %i[create update]
      resources :listings, only: %i[index edit update destroy]
      resources :listing_categories, only: %i[index edit update new create
                                              destroy], path: "listings/categories"

      resources :comments, only: [:index]
      resources :events, only: %i[index create update]
      resources :feedback_messages, only: %i[index show]
      resources :invitations, only: %i[index new create]
      resources :pages, only: %i[index new create edit update destroy]
      resources :mods, only: %i[index update]
      resources :moderator_actions, only: %i[index]
      resources :navigation_links, only: %i[index update create destroy]
      resources :privileged_reactions, only: %i[index]
      resources :permissions, only: %i[index]
      resources :podcasts, only: %i[index edit update destroy] do
        member do
          post :fetch
          post :add_admin
          delete :remove_admin
        end
      end

      resources :profile_field_groups, only: %i[update create destroy]
      resources :profile_fields, only: %i[index update create destroy]
      resources :reactions, only: [:update]
      resources :response_templates, only: %i[index new edit create update destroy]
      resources :chat_channels, only: %i[index create update destroy] do
        member do
          delete :remove_user
        end
      end
      resources :reports, only: %i[index show], controller: "feedback_messages" do
        collection do
          post "send_email"
          post "create_note"
          post "save_status"
        end
      end
      resources :tags, only: %i[index update show]
      resources :users, only: %i[index show edit update] do
        member do
          post "banish"
          post "full_delete"
          patch "user_status"
          post "merge"
          delete "remove_identity"
          post "send_email"
          post "verify_email_ownership"
          patch "unlock_access"
        end
      end
      resources :organization_memberships, only: %i[update destroy create]
      resources :organizations, only: %i[index show] do
        member do
          patch "update_org_credits"
        end
      end
      resources :sponsorships, only: %i[index edit update new create destroy]
      resources :welcome, only: %i[index create]
      resources :growth, only: %i[index]
      resources :tools, only: %i[index create] do
        collection do
          post "bust_cache"
        end
      end
      resources :webhook_endpoints, only: :index
      resource :config
      resources :badges, only: %i[index edit update new create]
      resources :display_ads, only: %i[index edit update new create destroy]

      resources :html_variants, only: %i[index edit update new create show destroy]
      get "/badges/badge_achievements", to: redirect("/admin/badge_achievements")
      get "/badges/badge_achievements/award_badges", to: redirect("/admin/badge_achievements/award_badges")
      resources :badge_achievements, only: %i[index destroy]
      get "/badge_achievements/award_badges", to: "badge_achievements#award"
      post "/badge_achievements/award_badges", to: "badge_achievements#award_badges"
      resources :secrets, only: %i[index]
      put "secrets", to: "secrets#update"
    end

    namespace :stories, defaults: { format: "json" } do
      resource :feed, only: [:show] do
        get ":timeframe" => "feeds#show"
      end
    end

    namespace :api, defaults: { format: "json" } do
      scope module: :v0,
            constraints: ApiConstraints.new(version: 0, default: true) do
        resources :articles, only: %i[index show create update] do
          collection do
            get "me(/:status)", to: "articles#me", as: :me, constraints: { status: /published|unpublished|all/ }
            get "/:username/:slug", to: "articles#show_by_slug", as: :slug
          end
        end
        resources :comments, only: %i[index show]
        resources :videos, only: [:index]
        resources :podcast_episodes, only: [:index]
        resources :users, only: %i[show] do
          collection do
            get :me
          end
        end
        resources :tags, only: [:index]
        resources :follows, only: [:create] do
          collection do
            get :tags
          end
        end
        namespace :followers do
          get :users
          get :organizations
        end
        resources :webhooks, only: %i[index create show destroy]

        resources :listings, only: %i[index show create update]
        get "/listings/category/:category", to: "listings#index", as: :listings_category
        get "/analytics/totals", to: "analytics#totals"
        get "/analytics/historical", to: "analytics#historical"
        get "/analytics/past_day", to: "analytics#past_day"
        get "/analytics/referrers", to: "analytics#referrers"

        resources :health_checks, only: [] do
          collection do
            get :app
            get :search
            get :database
            get :cache
          end
        end
      end
    end

    namespace :notifications do
      resources :counts, only: [:index]
      resources :reads, only: [:create]
    end

    namespace :incoming_webhooks do
      get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
      post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
    end

    resources :messages, only: [:create]
    resources :chat_channels, only: %i[index show create update]
    resources :chat_channel_memberships, only: %i[index create edit update destroy]
    resources :articles, only: %i[update create destroy] do
      patch "/admin_unpublish", to: "articles#admin_unpublish"
    end
    resources :article_mutes, only: %i[update]
    resources :comments, only: %i[create update destroy] do
      patch "/hide", to: "comments#hide"
      patch "/unhide", to: "comments#unhide"
      patch "/admin_delete", to: "comments#admin_delete"
      collection do
        post "/moderator_create", to: "comments#moderator_create"
      end
    end
    resources :comment_mutes, only: %i[update]
    resources :users, only: %i[index], defaults: { format: :json } # internal API
    resources :users, only: %i[update] do
      resource :twitch_stream_updates, only: %i[show create]
    end
    resources :twitch_live_streams, only: :show, param: :username
    resources :reactions, only: %i[index create]
    resources :response_templates, only: %i[index create edit update destroy]
    resources :feedback_messages, only: %i[index create]
    resources :organizations, only: %i[update create destroy]
    resources :followed_articles, only: [:index]
    resources :follows, only: %i[show create update] do
      collection do
        get "/bulk_show", to: "follows#bulk_show"
      end
    end
    resources :image_uploads, only: [:create]
    resources :notifications, only: [:index]
    resources :tags, only: [:index] do
      collection do
        get "/onboarding", to: "tags#onboarding"
      end
    end
    resources :stripe_active_cards, only: %i[create update destroy]
    resources :github_repos, only: %i[index] do
      collection do
        post "/update_or_create", to: "github_repos#update_or_create"
      end
    end
    resources :buffered_articles, only: [:index]
    resources :events, only: %i[index show]
    resources :videos, only: %i[index create new]
    resources :video_states, only: [:create]
    resources :twilio_tokens, only: [:show]
    resources :html_variant_trials, only: [:create]
    resources :html_variant_successes, only: [:create]
    resources :tag_adjustments, only: %i[create destroy]
    resources :rating_votes, only: [:create]
    resources :page_views, only: %i[create update]
    resources :listings, only: %i[index new create edit update destroy dashboard]
    resources :credits, only: %i[index new create] do
      get "purchase", on: :collection, to: "credits#new"
    end
    resources :buffer_updates, only: [:create]
    resources :reading_list_items, only: [:update]
    resources :poll_votes, only: %i[show create]
    resources :poll_skips, only: [:create]
    resources :profile_pins, only: %i[create update]

app/controllers/admin/tags_controller.rb
module Admin
  class TagsController < Admin::ApplicationController
    layout "admin"

    after_action only: [:update] do
      Audit::Logger.log(:moderator, current_user, params.dup)
    end

    def index
      @tags = case params[:state]
              when "supported"
                Tag.where(supported: true).order(taggings_count: :desc).page(params[:page]).per(50)
              when "unsupported"
                Tag.where(supported: false).order(taggings_count: :desc).page(params[:page]).per(50)
              else
                Tag.order(taggings_count: :desc).page(params[:page]).per(50)
              end
      @tags = @tags.where("tags.name ILIKE :search", search: "%#{params[:search]}%") if params[:search].present?
    end

    def show
      @tag = Tag.find(params[:id])
    end

    def update
      @tag = Tag.find(params[:id])
      @add_user_id = params[:tag][:tag_moderator_id]
      @remove_user_id = params[:tag][:remove_moderator_id]
      add_moderator if @add_user_id
      remove_moderator if @remove_user_id
      @tag.update!(tag_params)

      redirect_to "/admin/tags/#{params[:id]}"
    end

    private

    def remove_moderator
      user = User.find(@remove_user_id)
      user.update(email_tag_mod_newsletter: false)
      AssignTagModerator.remove_tag_moderator(user, @tag)
    end

    def add_moderator
      User.find(@add_user_id).update(email_tag_mod_newsletter: true)
      AssignTagModerator.add_tag_moderators([@add_user_id], [@tag.id])
    end

    def tag_params
      allowed_params = %i[
        supported rules_markdown short_summary pretty_name bg_color_hex
        text_color_hex tag_moderator_id remove_moderator_id alias_for badge_id
        category social_preview_template
      ]
      params.require(:tag).permit(allowed_params)
    end
  end
end

app/controllers/api/v0/tags_controller.rb
module Api
  module V0
    class TagsController < ApiController
      before_action :set_cache_control_headers, only: %i[index]

      ATTRIBUTES_FOR_SERIALIZATION = %i[id name bg_color_hex text_color_hex].freeze
      private_constant :ATTRIBUTES_FOR_SERIALIZATION

      def index
        page = params[:page]
        per_page = (params[:per_page] || 10).to_i
        num = [per_page, 1000].min

        @tags = Tag.select(ATTRIBUTES_FOR_SERIALIZATION)
          .order(taggings_count: :desc)
          .page(page).per(num)

        set_surrogate_key_header Tag.table_key, @tags.map(&:record_key)
      end
    end
  end
end

app/controllers/resource_admin/tags_controller.rb
module ResourceAdmin
  class TagsController < ResourceAdmin::ApplicationController
    def update
      @tag = Tag.find(params[:id])
      if @tag.update(tag_params) && @tag.errors.messages.blank?
        flash[:notice] = "Tag successfully updated"
        redirect_to "/resource_admin/tags/#{@tag.id}"
      else
        render :new, locals: { page: Administrate::Page::Form.new(dashboard, @tag) }
      end
    end

    private

    def convert_empty_string_to_nil
      # nil plays nicely with our hex colors, whereas empty string doesn't
      params[:tag][:text_color_hex] = nil if params[:tag][:text_color_hex] == ""
      params[:tag][:bg_color_hex] = nil if params[:tag][:bg_color_hex] == ""
    end

    def tag_params
      accessible = %i[
        name
        category
        badge_id
        supported
        alias_for
        wiki_body_markdown
        rules_markdown
        short_summary
        requires_approval
        submission_template
        pretty_name
        bg_color_hex
        text_color_hex
        keywords_for_search
        buffer_profile_id_code
      ]
      convert_empty_string_to_nil
      params.require(:tag).permit(accessible)
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_cache_control_headers, only: %i[index onboarding]
  before_action :authenticate_user!, only: %i[edit update]
  after_action :verify_authorized

  ATTRIBUTES_FOR_SERIALIZATION = %i[id name bg_color_hex text_color_hex].freeze

  def index
    skip_authorization
    @tags_index = true
    @tags = Tag.includes(:sponsorship).order(hotness_score: :desc).limit(100)
  end

  def edit
    @tag = Tag.find_by!(name: params[:tag])
    authorize @tag
  end

  def update
    @tag = Tag.find(params[:id])
    authorize @tag
    if @tag.errors.messages.blank? && @tag.update(tag_params)
      flash[:success] = "Tag successfully updated! 👍 "
      redirect_to "/t/#{URI.parse(@tag.name).path}/edit"
    else
      flash[:error] = @tag.errors.full_messages
      render :edit
    end
  end

  def admin
    tag = Tag.find_by!(name: params[:tag])
    authorize tag
    redirect_to "/resource_admin/tags/#{tag.id}/edit"
  end

  def onboarding
    skip_authorization

    @tags = Tag.where(name: SiteConfig.suggested_tags)
      .select(ATTRIBUTES_FOR_SERIALIZATION)

    set_surrogate_key_header Tag.table_key, @tags.map(&:record_key)
  end

  private

  def convert_empty_string_to_nil
    # nil plays nicely with our hex colors, whereas empty string doesn't
    params[:tag][:text_color_hex] = nil if params[:tag][:text_color_hex] == ""
    params[:tag][:bg_color_hex] = nil if params[:tag][:bg_color_hex] == ""
  end

  def tag_params
    accessible = %i[
      wiki_body_markdown
      rules_markdown
      short_summary
      pretty_name
      bg_color_hex
      text_color_hex
    ]
    convert_empty_string_to_nil
    params.require(:tag).permit(accessible)
  end

  private_constant :ATTRIBUTES_FOR_SERIALIZATION
end

app/views/tags/_liquid.html.erb
<div class="ltag__tag ltag__tag__id__<%= tag.id %>" style="border-color:<%= dark_color %>;box-shadow: 3px 3px 0px <%= dark_color %>;">
  <style>
    .ltag__tag__id__<%= tag.id %> .follow-action-button{
      background-color: <%= tag.bg_color_hex %> !important;
      color: <%= tag.text_color_hex %> !important;
      border-color: <%= tag.bg_color_hex.to_s.casecmp("#ffffff").zero? ? tag.text_color_hex : tag.bg_color_hex %> !important;
    }
  </style>
    <div class="ltag__tag__content">
      <h2>#<a href="/t/<%= tag.name %>" class="ltag__tag__link"><%= tag.name %></a> <%= follow_btn %></h2>
      <div class="ltag__tag__summary">
        <%= tag.short_summary %>
      </div>
    </div>
</div>

app/views/tags/edit.html.erb
<% title "Edit #{@tag.name}" %>

<%= javascript_packs_with_chunks_tag "colorPicker", defer: true %>

<style>
  .widget header {
    color: <%= HexComparer.new([@tag.bg_color_hex || "#0000000", @tag.text_color_hex || "#ffffff"]).brightness(0.8) %>
  }

  .slanty-accent {
    background-color: <%= HexComparer.new([@tag.bg_color_hex || "#ffffff"]).accent %>
  }

  .tag-edit-tag {
    text-align: center;
    color: <%= @tag.text_color_hex %>;
  }
</style>
<br>
<br>
<br>
<div class="user-profile-header tag-header" style="background-color:<%= @tag.bg_color_hex %>;color:<%= @tag.text_color_hex %>;">
  <div class="slanty-accent"></div>
  <div class="tag-or-query-header-container tag-edit-tag">
    <h1> Editing:
      <a href="/t/<%= @tag.name %>" style="color: <%= @tag.text_color_hex %>;text-decoration: underline;"><%= @tag.name %></a>
    </h1>
    <p>
      <code style="background-color: #D2D2D2; color: black; padding: 5px; border-radius: 5px;">#<%= @tag.name %></code> is the name of the tag used in Markdown.
    </p>
  </div>
</div>
<%= form_tag("/tag/#{@tag.id}", method: :patch, class: "tag-edit-form") do %>
  <div class="tag-edit-container">
    <% if flash[:success] %>
      <p class="tag-edit-flash-success">
        <%= flash[:success] %>
      </p>
    <% elsif flash[:error] %>
      <ul class="tag-edit-flash-error">
        <% flash[:error].each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <h4>
      <a target="_blank" rel="noopener" href="https://thepracticaldev.s3.amazonaws.com/i/cc8vz48djnhty6c31jog.png">
        Click here to see an example of attributes.
      </a>
    </h4>
    <div class="tag-form-field">
      <%= label_tag :pretty_name %>
      <br>
      <%= text_field_tag "tag[pretty_name]", @tag.pretty_name, placeholder: "This is the name at the top of the show page.", class: "tag-form-text-field" %>
    </div>
    <div class="tag-form-field">
      <%= label_tag :bg_color_hex %>
      <br>
      <%= text_field_tag "tag[bg_color_hex]", @tag.bg_color_hex, placeholder: "Click for color picker", class: "tag-form-text-field color-picker" %>
      <div class="color-palette"></div>
    </div>
    <div class="tag-form-field">
      <%= label_tag :text_color_hex %>
      <br>
      <%= text_field_tag "tag[text_color_hex]", @tag.text_color_hex, placeholder: "Click for color picker", class: "tag-form-text-field color-picker" %>
      <div class="color-palette"></div>
    </div>
    <div class="tag-form-field">
      <%= label_tag :short_summary %>
      <br>
      <%= text_area_tag "tag[short_summary]", @tag.short_summary, placeholder: "Brief overview of what this tag is all about.", class: "tag-form-text-field tag-area-text" %>
    </div>
    <div class="tag-form-field">
      <%= label_tag :wiki_body_markdown %>
      <br>
      <%= text_area_tag "tag[wiki_body_markdown]", @tag.wiki_body_markdown, placeholder: "This is an 'about' section. Feel free to add an FAQ, additional resources, etc.", class: "tag-form-text-field tag-area-text" %>
    </div>
    <div class="tag-form-field">
      <%= label_tag :rules_markdown %>
      <br>
      <%= text_area_tag "tag[rules_markdown]", @tag.rules_markdown, placeholder: "Optional - Can be used for challenges, i.e. submission guidelines.", class: "tag-form-text-field tag-area-text" %>
    </div>
    <div class="tag-form-field">
      <%= submit_tag "SAVE CHANGES", class: "tag-edit-submit" %>
    </div>
  </div>
<% end %>

<% if current_user.has_role?(:super_admin) || current_user.has_role?(:admin) %>
  <center>
    <h1><a href="/admin/tags/<%= @tag.id %>" data-no-instant><%= @tag.name %> admin</a></h1>
    <br />
    <br />
    <br />
  </center>
<% end %>

app/views/tags/index.html.erb
<% title "Tags on #{community_name}" %>

<%= content_for :page_meta do %>
  <link rel="canonical" href="<%= app_url("/about") %>" />
  <meta name="description" content="Tags to follow on <%= community_name %>">
  <meta name="keywords" content="<%= SiteConfig.meta_keywords[:default] %>">

  <meta property="og:type" content="article" />
  <meta property="og:url" content="<%= app_url("/about") %>" />
  <meta property="og:title" content="Tags to follow on <%= community_name %>" />
  <meta property="og:image" content="<%= SiteConfig.main_social_image %>" />
  <meta property="og:description" content="<%= community_qualified_name %> is great!" />
  <meta property="og:site_name" content="<%= community_qualified_name %>" />

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@<%= SiteConfig.social_media_handles["twitter"] %>">
  <meta name="twitter:title" content="About <%= community_name %>">
  <meta name="twitter:description" content="<%= community_qualified_name %> is great!">
  <meta name="twitter:image:src" content="<%= SiteConfig.main_social_image %>">
<% end %>

<div class="crayons-layout crayons-layout--1-col">
  <header class="px-2 m:px-0">
    <h1>Top tags</h1>
  </header>

  <div class="grid gap-2 m:gap-4 l:gap-6 m:grid-cols-2 l:grid-cols-3 px-2 m:px-0">
    <% @tags.each do |tag| %>
      <% color = HexComparer.new([tag.bg_color_hex || "#0000000", tag.text_color_hex || "#ffffff"]).brightness(0.8) %>
      <div class="tag-card crayons-card branded-4 p-4 m:p-6 m:pt-4 flex flex-col relative" style="border-top-color: <%= color %>; ">
        <h3 class="crayons-tag crayons-tag--l mb-2">
          <a href="/t/<%= tag.name %>" class="crayons-link">
            <span class="crayons-tag__prefix">#</span><%= tag.name %>
          </a>
        </h3>
        <% if tag.short_summary.present? %>
          <p class="mb-2 color-base-70 truncate-at-3"><%= sanitize tag.short_summary %></p>
        <% end %>
        <p class="mb-3 fs-s color-base-60">
          <%= pluralize tag.taggings_count, "post" %> published
          <% if tag.sponsorship && tag.sponsorship.status == "live" && tag.sponsorship.expires_at > Time.current %>
          | Sponsored by <%= tag.sponsorship.organization.name %> ❤️
          <% end %>
        </p>

        <% if tag %>
          <div class="mt-auto">
            <button
              class="crayons-btn crayons-btn--secondary follow-action-button"
              data-info='{"id":<%= tag.id %>,"className":"Tag", "followStyle":"secondary"}'>
              Follow
            </button>
          </div>
        <% end %>

        <% if tag.badge_id && tag.badge %>
          <img src="<%= optimized_image_url(tag.badge.badge_image_url, width: 180) %>" style="width: 64px; height: 64px; transform: rotate(<%= -25 + (tag.id.digits.first * 5) %>deg);" class="right-1 bottom-1 absolute" />
        <% end %>
      </div>
    <% end %>
  </div>
</div>